INSERT INTO PA165.CUSTOMER (ADDRESS, ENABLED, FIRSTNAME, LEGALSTATUS, PASSWORD, "ROLE", SECONDNAME, USERNAME) VALUES ('adminova', false, 'admin', 0, '$2a$10$88qoEUehVtLqNMYmPaPjUOGjm8F3nQ6gsBd0Amf7FY9fvliz1Y/tC', 0, 'admin', 'admin');

